## Used car Price Prediction 
This dataset comprises used cars sold onthe cardekho.com in India as well as important features of these cars.

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("cardekho_imputated.csv")

In [4]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [5]:
df.describe

<bound method NDFrame.describe of        Unnamed: 0         car_name     brand     model  vehicle_age  \
0               0      Maruti Alto    Maruti      Alto            9
1               1    Hyundai Grand   Hyundai     Grand            5
2               2      Hyundai i20   Hyundai       i20           11
3               3      Maruti Alto    Maruti      Alto            9
4               4    Ford Ecosport      Ford  Ecosport            6
...           ...              ...       ...       ...          ...
15406       19537      Hyundai i10   Hyundai       i10            9
15407       19540    Maruti Ertiga    Maruti    Ertiga            2
15408       19541      Skoda Rapid     Skoda     Rapid            6
15409       19542  Mahindra XUV500  Mahindra    XUV500            5
15410       19543       Honda City     Honda      City            2

       km_driven seller_type fuel_type transmission_type  mileage  engine  \
0         120000  Individual    Petrol            Manual    19.70     796
1          20000  Individual    Petrol            Manual    18.90    1197
2          60000  Individual    Petrol            Manual    17.00    1197
3          37000  Individual    Petrol            Manual    20.92     998
4          30000      Dealer    Diesel            Manual    22.77    1498
...          ...         ...       ...               ...      ...     ...
15406      10723      Dealer    Petrol            Manual    19.81    1086
15407      18000      Dealer    Petrol            Manual    17.50    1373
15408      67000      Dealer    Diesel            Manual    21.14    1498
15409    3800000      Dealer    Diesel            Manual    16.00    2179
15410      13000      Dealer    Petrol         Automatic    18.00    1497

       max_power  seats  selling_price
0          46.30      5         120000
1          82.00      5         550000
2          80.00      5         215000
3          67.10      5         226000
4          98.59      5         570000
...          ...    ...            ...
15406      68.05      5         250000
15407      91.10      7         925000
15408     103.52      5         425000
15409     140.00      7        1225000
15410     117.60      5        1200000

[15411 rows x 14 columns]>

## Data Cleaning
### Handling missing values 
* Handling missing values 
* Handling Duplicates
* Check data type 
* Understand the data

In [6]:
# checking the null values 
# checking features with nan values
df.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [7]:
#removing unnecessary columns
df.drop(['car_name','brand'],inplace=True,axis=1)

In [8]:
df.head(5)

,Unnamed: 0,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [9]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [10]:
# Getting all different types of features 
num_features=[feature for feature in df.columns  if df[feature].dtype !='o']
print("Number of Numerical Features: ",len(num_features))
cat_features=[feature for feature in df.columns if df[feature].dtype=='o']
print("Number of Categorical Features:",len(cat_features))
dicsrete_feature=[feature for feature in num_features if len(df[feature].unique())<=25]
print("Number of Discrete Features: ",len(dicsrete_feature))
cont_features=[feature for feature in num_features if feature not in dicsrete_feature]
print("Number of Continuous Features: ",len(cont_features))

Number of Numerical Features:  12
Number of Categorical Features: 0
Number of Discrete Features:  5
Number of Continuous Features:  7

In [11]:
##Independent and Dependent Features 
from sklearn.model_selection import train_test_split
X=df.drop(['selling_price'],axis=1)
y=df['selling_price']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [ ]:
X.head(5)

,Unnamed: 0,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

## Feature Encoding and Scaling  
One hot encoding for Columns which has lesser unique values and not ordinal

In [13]:
len(df['model'].unique())

120

In [14]:
df['model'].value_counts()

model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

In [15]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [16]:
X['model']=le.fit_transform(X['model'])

In [17]:
X.head()

,Unnamed: 0,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [18]:
len(df['seller_type'].unique()),len(df['fuel_type'].unique()),len(df['transmission_type'].unique())

(3, 5, 2)

In [19]:
#Creating a column transformer with three (3) types of transformers
num_features=X.select_dtypes(exclude="object").columns
onehot_columns=['seller_type','fuel_type','transmission_type']

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer



numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop='first')

preprocessing=ColumnTransformer(
    [  ("OneHotEncoder",oh_transformer,onehot_columns)
     ,("StandardScaler",numeric_transformer,num_features)

    ],remainder='passthrough'
)

In [20]:
X=preprocessing.fit_transform(X)

In [21]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.738694,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.738516,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.738339,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.738162,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-1.737985,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.723327,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.723859,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.724036,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.724213,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.724391,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [22]:
#Seperating Dataset into Train and Test 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape

((12328, 15), (3083, 15))

In [23]:
X_train

array([[ 0.        ,  0.        ,  1.        , ...,  1.75390551,
         2.66249771, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55087963,
        -0.38602844, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  0.89033072,
         3.27453006, -0.40302241],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.9366097 ,
        -0.78070786, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43582879, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.04616815,
         0.06194201, -0.40302241]], shape=(12328, 15))

## Model Training and Model Selection

In [24]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor 
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [ ]:
## Starting the Model training 
models={
    "Linear Regression":LinearRegression(),
    "Lasso":Lasso(),
    "Ridge":Ridge(),
    "K-Neighbors Regressor":KNeighborsRegressor(),
    "Decision Tree Regressor":DecisionTreeRegressor(),
    "Random Forest Regressor":RandomForestRegressor(),
}

for i in range (len(list(models))):
    model=list(models.values())[i]
    model.fit (X_train,y_train)


    #Making predictions 
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)

    #Evaluating the train and  test data 
    model_train_mae=mean_absolute_error(y_train,y_train_pred)
    model_train_rmse=np.sqrt(mean_squared_error(y_train,y_train_pred))
    model_train_r2=r2_score(y_train,y_train_pred)


    model_test_mae=mean_absolute_error(y_test,y_test_pred)
    model_test_rmse=np.sqrt(mean_squared_error(y_test,y_test_pred))
    model_test_r2=r2_score(y_test,y_test_pred)
    
   
    #model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    #model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)


   
   
    print(list(models.keys())[i])
    print("Model Performance for Training Dataset")
    print("-Root Mean Square Error:{:.4f} ".format(model_train_rmse))
    print("-Mean Absolute Error:{:.4f} ".format(model_train_mae))
    print("-R2 Score: {:.4f}".format(model_train_r2))


    print("-----------------------------------------------")

    
    
    
    print("Model Performance for Test Dataset")
    print("-Root Mean Square Error:{:.4f} ".format(model_test_rmse))
    print("-Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("-R2 Score:{:.4f} ".format(model_test_r2))

    print('='*35)
    print('/n')

Linear Regression
Model Performance for Training Dataset
-Root Mean Square Error:553850.0494
-Mean Absolute Error:268104.1303
-R2 Score: 0.6218
-----------------------------------------------
Model Performance for Test Dataset
-Root Mean Square Error:502582.0834
-Mean Absolute Error: 279686.6479
-R2 Score:0.6645
===================================
/n
Lasso
Model Performance for Training Dataset
-Root Mean Square Error:553850.0538
-Mean Absolute Error:268101.7491
-R2 Score: 0.6218
-----------------------------------------------
Model Performance for Test Dataset
-Root Mean Square Error:502581.1494
-Mean Absolute Error: 279682.7929
-R2 Score:0.6645
===================================
/n
Ridge
Model Performance for Training Dataset
-Root Mean Square Error:553850.6941
-Mean Absolute Error:268061.4421
-R2 Score: 0.6218
-----------------------------------------------
Model Performance for Test Dataset
-Root Mean Square Error:502572.3576
-Mean Absolute Error: 279625.1576
-R2 Score:0.6645
===================================
/n
K-Neighbors Regressor
Model Performance for Training Dataset
-Root Mean Square Error:335460.8145
-Mean Absolute Error:96905.2401
-R2 Score: 0.8612
-----------------------------------------------
Model Performance for Test Dataset
-Root Mean Square Error:302364.2710
-Mean Absolute Error: 124343.6669
-R2 Score:0.8786
===================================
/n
Decision Tree Regressor
Model Performance for Training Dataset
-Root Mean Square Error:0.0000
-Mean Absolute Error:0.0000
-R2 Score: 1.0000
-----------------------------------------------
Model Performance for Test Dataset
-Root Mean Square Error:325202.2651
-Mean Absolute Error: 130509.5281
-R2 Score:0.8595
===================================
/n
Random Forest Regressor
Model Performance for Training Dataset
-Root Mean Square Error:142095.8702
-Mean Absolute Error:36533.0248
-R2 Score: 0.9751
-----------------------------------------------
Model Performance for Test Dataset
-Root Mean Square Error:240463.8871
-Mean Absolute Error: 98989.2751
-R2 Score:0.9232
===================================
/n

In [32]:
# Initializing few parameters for Hyper parameter tuning
knn_params={"n_neighbors":[2,3,10,20,40,50]}
rf_params={"max_depth":[5,8,15,None,10],
           "max_features":[5,7,"auto",8],
           "min_samples_split":[2,8,15,20],
           "n_estimators":[100,200,500,1000]}

In [ ]:
#Model list for Hyperparameter Tuning
randomcv_models=[("KNN",KNeighborsRegressor(),knn_params),
                 ("RF",RandomForestRegressor(),rf_params)]

## Hyper Parameter Tunining

In [34]:
from sklearn.model_selection import RandomizedSearchCV

model_params={}
for name,model,params in randomcv_models:
    random=RandomizedSearchCV(estimator=model,param_distributions=params,n_iter=100,cv=3,verbose=2,n_jobs=-1)

    random.fit(X_train,y_train)
    model_params[name]=random.best_params_

    for model_name in model_params:
        print(f"-----------------Best Params for {model_name}-------------------")
        print(model_params[model_name])

d:\python1\venv\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 6 is smaller than n_iter=100. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 3 folds for each of 6 candidates, totalling 18 fits
-----------------Best Params for KNN-------------------
{'n_neighbors': 2}
Fitting 3 folds for each of 100 candidates, totalling 300 fits

d:\python1\venv\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
87 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
44 fits failed with the following error:
Traceback (most recent call last):
  File "d:\python1\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\python1\venv\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "d:\python1\venv\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "d:\python1\venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
43 fits failed with the following error:
Traceback (most recent call last):
  File "d:\python1\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\python1\venv\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "d:\python1\venv\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "d:\python1\venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
d:\python1\venv\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.82531338 0.84021973 0.81800234 0.84362698
 0.82828489        nan 0.84075444 0.8350897  0.85688274 0.84053743
        nan 0.85055645        nan 0.79213312        nan        nan
 0.84415428 0.83724728        nan        nan        nan 0.85070802
 0.85574312 0.79829409        nan 0.84083087 0.82424648 0.8301567
        nan        nan 0.84136541        nan 0.7877267         nan
 0.81494174        nan 0.84023822 0.85574964 0.84700104 0.84225073
 0.84317077 0.85245057 0.82106538 0.83735911 0.83580185 0.8156715
 0.83032749 0.83063061        nan 0.84429559 0.84095887 0.84234392
        nan        nan        nan 0.84888397        nan 0.82665783
 0.85674761 0.85630399 0.83429099        nan 0.84478972        nan
 0.85398331 0.79574668 0.78827621        nan 0.82982068 0.8433875
 0.79325862 0.76409355 0.78864164 0.81172749 0.83270883 0.83279937
 0.82912235        nan 0.83514073 0.85002436 0.83615367 0.83625755
 0.85681204 0.77565021 0.83754938        nan        nan 0.82480258
 0.76171688 0.85414936 0.8280726  0.84142531        nan 0.82772454
 0.83961505 0.83330479 0.79460613        nan]
  warnings.warn(

-----------------Best Params for KNN-------------------
{'n_neighbors': 2}
-----------------Best Params for RF-------------------
{'n_estimators': 500, 'min_samples_split': 2, 'max_features': 5, 'max_depth': None}

In [35]:
#Retraining the model with best parameter
models= {
    "Random Forest Regression": RandomForestRegressor(n_estimators=500, min_samples_split= 2,max_features= 5, max_depth=None),
    "K-Neighbors Regression":KNeighborsRegressor(n_neighbors=2)

}
for i in range (len(list(models))):
    model=list(models.values())[i]
    model.fit (X_train,y_train)


    #Making predictions 
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)

    #Evaluating the train and  test data 
    model_train_mae=mean_absolute_error(y_train,y_train_pred)
    model_train_rmse=np.sqrt(mean_squared_error(y_train,y_train_pred))
    model_train_r2=r2_score(y_train,y_train_pred)


    model_test_mae=mean_absolute_error(y_test,y_test_pred)
    model_test_rmse=np.sqrt(mean_squared_error(y_test,y_test_pred))
    model_test_r2=r2_score(y_test,y_test_pred)
    
   
    #model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    #model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)


   
   
    print(list(models.keys())[i])
    print("Model Performance for Training Dataset")
    print("-Root Mean Square Error:{:.4f} ".format(model_train_rmse))
    print("-Mean Absolute Error:{:.4f} ".format(model_train_mae))
    print("-R2 Score: {:.4f}".format(model_train_r2))


    print("-----------------------------------------------")

    
    
    
    print("Model Performance for Test Dataset")
    print("-Root Mean Square Error:{:.4f} ".format(model_test_rmse))
    print("-Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("-R2 Score:{:.4f} ".format(model_test_r2))

    print('='*35)
    print('/n')

Random Forest Regression
Model Performance for Training Dataset
-Root Mean Square Error:128194.0737
-Mean Absolute Error:35486.9016
-R2 Score: 0.9797
-----------------------------------------------
Model Performance for Test Dataset
-Root Mean Square Error:210737.8280
-Mean Absolute Error: 94716.8204
-R2 Score:0.9410
===================================
/n
K-Neighbors Regression
Model Performance for Training Dataset
-Root Mean Square Error:223571.1288
-Mean Absolute Error:69173.6697
-R2 Score: 0.9384
-----------------------------------------------
Model Performance for Test Dataset
-Root Mean Square Error:325340.8984
-Mean Absolute Error: 126154.2734
-R2 Score:0.8594
===================================
/n